export const styles = {
  container: {
    padding: '20px',
    fontFamily: 'system-ui',
    direction: 'ltr',
    maxWidth: '1400px',
    margin: '0 auto',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    justifyContent: 'flex-start',
    minHeight: '100vh',
    position: 'relative',
    top: 0,
  },
  header: { borderBottom: '2px solid #333', marginBottom: '20px' },
  title: { fontSize: '24px', fontWeight: '800' },
  adminPanel: {
    display: 'flex',
    gap: '8px',
    background: '#fff',
    padding: '15px',
    borderRadius: '10px',
    marginBottom: '20px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.05)',
  },
  input: {
    padding: '10px',
    border: '1px solid #ddd',
    borderRadius: '6px',
    flex: 1,
  },
  btnAdd: {
    background: '#007aff',
    color: 'white',
    padding: '10px 20px',
    border: 'none',
    borderRadius: '6px',
    fontWeight: 'bold',
  },
  btnReset: {
    background: '#ff3b30',
    color: 'white',
    padding: '10px 15px',
    border: 'none',
    borderRadius: '6px',
  },
  tableWrapper: {
    background: 'white',
    borderRadius: '10px',
    overflow: 'hidden',
    boxShadow: '0 2px 10px rgba(0,0,0,0.05)',
  },
  table: { width: '100%', borderCollapse: 'collapse' },
  th: {
    padding: '12px',
    backgroundColor: '#f8f9fa',
    fontSize: '12px',
    color: '#666',
  },
  tr: { borderBottom: '1px solid #eee' },
  td: { padding: '12px', textAlign: 'center' },
  tdName: { padding: '12px', textAlign: 'center', fontWeight: 'bold' },
  cell: {
    border: '1px solid #eee',
    padding: '15px',
    textAlign: 'center',
    cursor: 'pointer',
    fontWeight: 'bold',
    fontSize: '18px',
  },
  modal: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    background: 'rgba(0,0,0,0.98)',
    color: 'white',
    textAlign: 'center',
    zIndex: 10000,
    overflowY: 'auto',
  },
  modalContent: {
    paddingTop: '20px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  modalCategory: { fontSize: '16px', color: '#888', margin: '0' },
  modalName: { fontSize: '40px', margin: '5px 0' },
  modalWeight: {
    fontSize: '80px',
    color: '#f1c40f',
    margin: '0',
    lineHeight: '1',
  },
  stageSeparator: {
    minHeight: '120px',
    marginTop: '40px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  timer: {
    fontSize: '120px',
    fontWeight: 'bold',
    fontFamily: 'monospace',
    lineHeight: '1',
  },
  plateContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  barLine: {
    display: 'flex',
    alignItems: 'center',
    background: '#555',
    height: '10px',
    borderRadius: '5px',
    minWidth: '400px',
    marginBottom: '15px',
  },
  barCenter: {
    width: '80px',
    background: '#222',
    color: 'white',
    height: '24px',
    borderRadius: '3px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '10px',
    fontWeight: 'bold',
  },
  barSideLeft: {
    display: 'flex',
    flexDirection: 'row-reverse',
    alignItems: 'center',
    flex: 1,
    justifyContent: 'flex-start',
  },
  barSideRight: {
    display: 'flex',
    alignItems: 'center',
    flex: 1,
    justifyContent: 'flex-start',
  },
  plateDisc: {
    margin: '0 1.5px',
    borderRadius: '2px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loaderInstructions: {
    marginTop: '60px',
    background: 'rgba(255,255,255,0.05)',
    padding: '10px',
    borderRadius: '8px',
    fontSize: '18px',
  },
  instructionBadge: {
    margin: '0 8px',
    padding: '2px 5px',
    borderLeft: '1px solid #444',
  },
  actionContainer: {
    height: '80px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnStart: {
    background: '#007aff',
    color: 'white',
    padding: '12px 35px',
    fontSize: '20px',
    borderRadius: '8px',
    border: 'none',
    fontWeight: 'bold',
  },
  resultButtons: { display: 'flex', gap: '20px' },
  btnGood: {
    background: '#2ecc71',
    color: 'white',
    padding: '15px 40px',
    fontSize: '22px',
    border: 'none',
    borderRadius: '10px',
    fontWeight: 'bold',
  },
  btnBad: {
    background: '#e74c3c',
    color: 'white',
    padding: '15px 40px',
    fontSize: '22px',
    border: 'none',
    borderRadius: '10px',
    fontWeight: 'bold',
  },
  btnClose: {
    background: 'transparent',
    color: '#666',
    marginTop: '20px',
    border: '1px solid #333',
    padding: '8px 15px',
    borderRadius: '6px',
  },
};
